name: Check H5P library version

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  check-h5p-library-version:
    name: Check H5P if library version is updated

    runs-on: ubuntu-latest

    steps:
      - name: Find current PR number
        uses: jwalton/gh-find-current-pr@v1 # https://github.com/jwalton/gh-find-current-pr
        id: find-pr-number

      - name: Find comment
        uses: peter-evans/find-comment@v1 # https://github.com/peter-evans/find-comment
        id: find-comment
        with:
          issue-number: ${{ steps.find-pr-number.outputs.number }}
          comment-author: github-actions[bot]
          body-includes: <!-- h5p-library-check -->

      - name: Delete comment
        uses: sandeshjangam/comment-actions@v1 # https://github.com/sandeshjangam/comment-actions
        if: steps.find-comment.outputs.comment-id != ''
        with:
          type: delete
          comment_id: ${{ steps.find-comment.outputs.comment-id }}

      - name: Cancel workflow if PR has `non-functional` label
        uses: andymckay/cancel-action@0.2
        if: contains(github.event.pull_request.labels.*.name, 'non-functional')

      - name: Check if library is updated
        uses: boyum/is-h5p-library-updated-action@v1
        id: h5p-version-check

      - run: |
          echo '${{ steps.h5p-version-check.outputs.main-version }}'
          echo '${{ steps.h5p-version-check.outputs.current-version }}'

          echo '${{ steps.h5p-version-check.outputs.main-version-formatted }}'
          echo '${{ steps.h5p-version-check.outputs.current-version-formatted }}'

      - name: "Create comment: Version change missing"
        uses: peter-evans/create-or-update-comment@v1 # https://github.com/peter-evans/create-or-update-comment
        if: steps.h5p-version-check.outputs.is-ahead == 'false' && steps.find-comment.outputs.comment-id == ''
        with:
          issue-number: ${{ steps.find-pr-number.outputs.number }}
          body: |
            The library version was not updated. Add the label `non-functional` if this PR does not require a change of version numbers.

            Current version: ${{ steps.h5p-version-check.outputs.current-version-formatted }}
            Main version: ${{ steps.h5p-version-check.outputs.main-version-formatted }}
            <!-- h5p-library-check -->

      - name: "Create comment: Version changed"
        uses: peter-evans/create-or-update-comment@v1 # https://github.com/peter-evans/create-or-update-comment
        if: steps.h5p-version-check.outputs.is-ahead != 'false' && steps.find-comment.outputs.comment-id == ''
        with:
          issue-number: ${{ steps.find-pr-number.outputs.number }}
          body: |
            The library version was updated from ${{ steps.h5p-version-check.outputs.main-version-formatted }} to ${{ steps.h5p-version-check.outputs.current-version-formatted }}.
            <!-- h5p-library-check -->
